version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
  
  test:
    build: .
    command: ["go", "test", "-v", "./..."]  # This runs your Go tests
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=mydb
    networks:
      - app-network
    volumes:
      - .:/app

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
